name: Debug
on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Checkout code
        run: echo ----------
      - name: Checkout code
        run: echo $${{ secrets.RTG_CI_TOKEN }}
      - name: Checkout code
        run: echo ----------
