# As the main branch is protected, 
# this event can only be triggered after a pull request 
name: Deliver release
on: 
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          branch: "*"   
          extra_plugins: |
            semantic-release-helm3 
            @semantic-release/changelog@3.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: "${{ secrets.RTG_CI_TOKEN }}"
          HELM_REPO_USERNAME: admin
          HELM_REPO_PASSWORD: Retengr_31

